//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trial
    {
        public int ID { get; set; }
        public int ParticipantID { get; set; }
        public int TrialIndex { get; set; }
        public int TimeColour { get; set; }
        public int TimeNext { get; set; }
        public string Image { get; set; }
        public string Colour { get; set; }
        public int Slider { get; set; }
    
        public virtual Participant Participant { get; set; }
    }
}
